#pragma once

enum EAvalancheStatus{
	AVAL_SUCCESS,
	AVAL_NO_ERROR,
	
	AVAL_CLT_FAIL,
	AVAL_MULT_FAIL,
	AVAL_ERROR_GRID_NOT_EMPTY,
	AVAL_ERROR_TIMESTEP_EXCEEDING_LIMIT,
	AVAL_EXPLOSIVE_BEHAVIOR_CLT,
	AVAL_POTENTIAL_EXPLOSIVE_BEHAVIOR,
	AVAL_LONGI_DIFF_TIME_LIMIT_EXCEEDED
};
